##student multiple user
name=input("student name:-")
rollno=int(input("student enrollment no:-"))
marks1=int(input("marks no1:-"))
marks2=int(input("marks no2:-"))
marks3=int(input("marks no3:-"))
marks4=int(input("marks no4:-"))
marks5=int(input("marks no5:-"))
print("----students marksheet-----")
print(name)
print(rollno)
print(marks1)
print(marks2)
print(marks3)
print(marks4)
print(marks5)
